### ISSUE TITLE
Class 'SimpleJavaScriptCompilation\Model\Context' not found in ../libraries/CloudflareBypass/Model/UAM/UAMPageFormParams.php:57

### ISSUE THREAD

**Issue by nitemare** [KyranRana/cloudflare-bypass#166]
Getting the below error when i follow the example, what am i missing?

`[INFO] UAM (retry: 0) -> waiting for 5 seconds! [INFO] UAM (retry: 0) -> getting form params...
Fatal error: Uncaught Error: Class 'SimpleJavaScriptCompilation\Model\Context' not found in /home/nitemare/public_html/libraries/CloudflareBypass/Model/UAM/UAMPageFormParams.php:57 Stack trace: #0 /home/nitemare/public_html/libraries/CloudflareBypass/Model/UAM/UAMPageFormParams.php(41): CloudflareBypass\Model\UAM\UAMPageFormParams::getJschlAnswerFromPage(Object(CloudflareBypass\Model\UAM\UAMPageAttributes)) #1 /home/nitemare/public_html/libraries/CloudflareBypass/Model/UAM/UAMPageAttributes.php(55): CloudflareBypass\Model\UAM\UAMPageFormParams::getParamsFromPage(Object(CloudflareBypass\Model\UAM\UAMPageAttributes)) #2 /home/nitemare/public_html/libraries/CloudflareBypass/CFCurlImpl.php(146): CloudflareBypass\Model\UAM\UAMPageAttributes->__construct('http', 'torrentz2.is', '<!DOCTYPE HTML>...') #3 /home/nitemare/public_html/libraries/CloudflareBypass/CFCurlImpl.php(96): CloudflareBypass\CFCurlImpl->bypassIUAMPage(Resource id #33, '<!DOCTYPE HTML>...', Ar in /home/nitemare/public_html/libraries/CloudflareBypass/Model/UAM/UAMPageFormParams.php on line 57`

**Comment by nitemare** [comment]
other packages or required, this isn't explained as clearly as it should be, installing with the composer installs the packages
