### ISSUE TITLE
Errow on v1 version

### ISSUE THREAD

**Issue by Paul1427** [KyranRana/cloudflare-bypass#47]
Hi! I added v1 version into my plugin on worpress and today I give this error.

`Warning: A non-numeric value encountered in libraries/cloudflareClass.php(266) : eval()'d code on line 5

Fatal error: Uncaught Error: Call to undefined function toFixed() in libraries/cloudflareClass.php(266) : eval()'d code:5 Stack trace: #0 libraries/cloudflareClass.php(266): eval() #1 libraries/cloudflareClass.php(93): cloudflare::solveJavaScriptChallenge('https://see....', '<!DOCTYPE HTML>...') #2 libraries/cloudflareClass.php(58): cloudflare::bypassCloudFlare('https://seehd.u...', 'https://see...') #3 plugins/import plugin/import.php(68): cloudflare::bypass('https://see...') #4 /wp-includes/class-wp-hook.php(286): init('') #5 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) in libraries/cloudflareClass.php(266) : eval()'d code on line 5`

I used v1 version because is easier to add into wp and it's work perfect until today.

Code that i use

`require_once 'libraries/httpProxyClass.php';
require_once 'libraries/cloudflareClass.php';

$httpProxy   = new httpProxy();
$httpProxyUA = 'proxyFactory';

$requestLink = $url;
$requestPage = json_decode($httpProxy->performRequest($requestLink));

if($requestPage->status->http_code == 503) {
	cloudflare::useUserAgent($httpProxyUA);

	if($clearanceCookie = cloudflare::bypass($requestLink)) {
		$requestPage = $httpProxy->performRequest($requestLink, 'GET', null, array(
			'cookies' => $clearanceCookie
		));
		$requestPage = json_decode($requestPage);
		$html = $requestPage->content;
	}
} 	else {
		$html = @file_get_contents($url);
}`

Where $url can be one url or multiple url  array("https://site", "https://site2")

**Comment by NikitaKurdin** [comment]
The same error.

**Comment by dreamdeveloper** [comment]
I solved the problem, you need to add this line to the function solveJavaScriptChallenge "cloudflareClass.php"
`$script  = str_replace('.toFixed(10)' , '', $script);`
it works for me

**Comment by momala454** [comment]
are you able to use v2 ?

**Comment by dreamdeveloper** [comment]
if this is not enough, then here's another line of code that should help:
`$script  = preg_replace("/(answer)=.(\w+).(\w+)/i", '$1=$$2_$3', $script);`
since it works on one server, but on another server for some reason, without this line of code it's not working

> @momala454 No, I didn't use the second version.

**Comment by Paul1427** [comment]
@dreamdeveloper Which version of php do you use? With both line on php 7.2 I have same error. Can you tell me what version do you use? Also, on what line do you add  
`$script = preg_replace("/(answer)=.(\w+).(\w+)/i", '$1=$$2_$3', $script);`
I pun on function solveJavaScriptChallenge on top of `eval($script);` - line 264

**Comment by dreamdeveloper** [comment]
here is a screenshot of the function solveJavaScriptChallenge
PHP Version 5.6.34 | PHP Version 5.5.9
![fix_bugs](https://user-images.githubusercontent.com/10743142/38385600-f626314c-391a-11e8-84a0-9d768d2a0da4.png)

**Comment by Paul1427** [comment]
@dreamdeveloper thank you! I can confirm that code work also on php 7.2

**Comment by dreamdeveloper** [comment]
@Paul1427 ok, that's great!

**Comment by Paul1427** [comment]
Hm, yestarday it's working, now i get only "Could not fetch CloudFlare clearance cookie (most likely due to excessive requests)" . Anyone have same error?

**Comment by NikitaKurdin** [comment]
> Anyone have same error?
Yes, I have...

**Comment by ReModWrite** [comment]
you can see for fix https://github.com/KyranRana/cloudflare-bypass/issues/53

**Comment by KyranRana** [comment]
V1 is now deprecated and will no longer be maintained. 

Please use V2, you can look in v2/examples for example code snippets. Replace "vendor/autoload.php" with "src/autoload.php" until I get this package on packagist. 

@dreamdeveloper @Paul1427 @snnyk @momala454 @NikitaKurdin
